"this is a function"
"Co2"
"1"
"this is a function"
"Co1"
"2"
"resume"
"3"
"resume"
"4"
"second is here"
"5"
"first is here"
"6"
"=== Start ==="
"Worker A - step 1"
"Worker B - step 1"
"Worker A - step 2"
"Worker C - step 1"
"Main: first pause"
"Worker B - step 2"
"Worker B - step 3"
"Worker C - step 2"
"Main: second pause"
"Worker A - step 3"
"Worker A - finished!"
"Worker B - step 4"
"Worker B - step 5"
"Worker B - finished!"
"=== End ==="
